if __name__ == '__main__':
    preco_1 = int(input("Digit o valor do produto 1:"))
    qntd_1 = int(input("Digit a quantidade do produto 1:"))
    preco_2 = int(input("Digit o valor do produto 2:"))
    qntd_2 = int(input("Digit a quantidade do produto 2:"))
    preco_3 = int(input("Digit o valor do produto 3:"))
    qntd_3 = int(input("Digit a quantidade do produto 3:"))
    preco_4 = int(input("Digit o valor do produto 4:"))
    qntd_4 = int(input("Digit a quantidade do produto 4:"))
    preco_5 = int(input("Digit o valor do produto 5:"))
    qntd_5 = int(input("Digit a quantidade do produto 5:"))
